# Generated by Django 5.2.3 on 2025-07-21 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiqueconnexion',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='message',
            name='destinataire',
        ),
        migrations.RemoveField(
            model_name='message',
            name='expediteur',
        ),
        migrations.DeleteModel(
            name='FichierScanne',
        ),
        migrations.DeleteModel(
            name='HistoriqueConnexion',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
